### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by instantkaffee** [sebastienwindal/FRD3DBarChart#5]
The background color of the view is set to black by default.
How to override to any UIColor ?

**Comment by aisliuyifei** [comment]
line 1812 
    glClearColor(0.0f, 0.0f, 0.0f, 0.0f);
you can change the backgroundcolor here,
But after changing it to be white, you would also need to change the legend colors. Things got odd when using those three legendColor delegate functions.

**Comment by instantkaffee** [comment]
Done
